### ISSUE TITLE
Host Automation API didn't get updated to support new protocols

### ISSUE THREAD

**Issue by eatondan** [NIVeriStandAdd-Ons/Diagnostics-Custom-Device#1]
The TCP host automation API works for GMLAN but did not get updated to fully support the addition of UDS and KWP.  Specifically review the messages are DTCs.

**Comment by zhangNing1988** [comment]
Hi Daniel Eaton,

This is Ning from EON in China.Now we should use VeriStand add a customer device to do diagnostic in RT system. As your comment that"The TCP host automation API works for GMLAN but did not get updated to fully support the addition of UDS and KWP".Now we need a customer device that support UDS. Can you provide  a customer device that support UDS?

Best regards.

Ning

**Comment by eatondan** [comment]
This has been updated.  UDS is now supported.
