### ISSUE TITLE
Errors with VIPM

### ISSUE THREAD

**Issue by AldhairG** [NIVeriStandAdd-Ons/Diagnostics-Custom-Device#2]
I am new to the community I don't really know how to properly install this **Diagnostics Custom Device.**

I've installed all dependencies with the VI Package Manager, even the ones that didn't have the .vipb file.

The problem occurs when I make and run the Build of the Diagnostics Custom Device on VIPM. 
After aprox. 40 Minutes i get an Error   The First file does exist but its a broken(or bad?) VI.

If it helps, I am using LabVIEW 2016(All dependecies were installed for 2016) Veristand 2016 and VIPM is updated.
I would appreciate any comment on this. Thank you.
[
![vipm -error details](https://user-images.githubusercontent.com/38099182/38410238-59c45e18-3984-11e8-883e-61fac50782cb.png)
](url)
![brokenvi](https://user-images.githubusercontent.com/38099182/38411413-55c97fa2-3987-11e8-8c9c-938d4e3203bd.PNG)
![brokenvi_2](https://user-images.githubusercontent.com/38099182/38411416-55e13106-3987-11e8-9797-e6aa904e6174.PNG)

**Comment by AldhairG** [comment]
As a comment i get the exact same Error with 2015 in another Computer.
Is there any special Step in the Installation that I'm probably missing?

**Comment by tannerblair** [comment]
@AldhairG , why are you trying to use VIPM for this? Custom Devices are distributed through build specs in the project, not as VI packages. If you're unfamiliar with the build process for Custom Devices, I would recommend you reach out to your local NI rep.

**Comment by AldhairG** [comment]
I just did what you say 1 hour ago. Yes I was unfamiliar with this but now
the problem is solved. Thanks for your answer. It was funny that I just
discovered that and you told me about it one second later.

What do you mean with  reach out my "local NI representative"​? I can ask
him questions or how can he help me?



2018-04-11 18:10 GMT+02:00 Tanner Blair <notifications@github.com>:

**Comment by tannerblair** [comment]
I am not familiar with how your region works, but there should be a sales rep for your area. They have the ability to request support if you're having issues.
