### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by AldhairG** [NIVeriStandAdd-Ons/Diagnostics-Custom-Device#3]
I don't know if this is a bug. And if it is a bug I don't know if it's important.
![2018-07-12_10-09-44](https://user-images.githubusercontent.com/38099182/42620722-0d67d4d0-85bc-11e8-909e-fd096585aa4d.gif)
It happens if I leave the blinking cursor at the beginning of the number and then try to change the Numeric System. Then Veristand crashes and the Target continue as nothing happened.

**Comment by eatondan** [comment]
I apologize. I have seen that before. It is a bug with the VeriStand Workspace and not the addon.
